service: audemos
#app: AUDEMOS

frameworkVersion: ">=1.1.0"

provider:
  stage: dev
  region: us-east-1

  name: aws
  runtime: nodejs18.x

  environment:
    REGION: ${self:provider.region}
    S3_AUDIO_BUCKET: ${self:service}-${self:provider.stage}-demos
  
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_AUDIO_BUCKET}/*"

functions:
  getURL:
    handler: handler.getURL
    events:
      - http:
          path: getURL
          method: post
          cors: true
  getFileURL:
    handler: handler.getFileURL
    events:
      - http:
          path: getFileURL
          method: post
          cors: true

package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - website/**
    - .gitignore

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_AUDIO_BUCKET}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
              AllowedOrigins:
              - "*"
              AllowedHeaders:
              - "*"
        LifecycleConfiguration:
          Rules:
            - Status: "Enabled"
              ExpirationInDays: 3
